### ISSUE TITLE
RxSession.fetch()

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-rx#18]
Instead of doing what we had previously talked about to allow async lazy loading, I propose a much simpler solution:

    rxSession.fetch( book.getAuthors() ).thenAccept( authors -> { ... } )

That's not much more code than the previous proposal, and is *much* less intrusive on the domain model classes, allowing people to use keep existing domain models.

This also looks *waaaay* easier to implement. We can just hook into whatever `Hibernate.initialize()` uses for this.

**Comment by gavinking** [comment]
@DavideD @Sanne @FroMage @emmanuelbernard WDYT?

**Comment by FroMage** [comment]
As a workaround until we get support for real async types, sure. But it's pretty intrusive on use-site compared to `book.getAuthors().thenAccept( authors -> { ... } )`.

We can definitely keep this even when we support real async relations, for the people who don't want to update their model classes, but for those starting with new entities (and in Quarkus if they use Panache they will likely start from new entities) it's suboptimal.

Also keep in mind we want to allow variations in relation types such as `CompletionStage<List<Foo>>` (lazy list), `Publisher<Foo>` (lazy stream), but also `Uni<List<Foo>>` and `Multi<Foo>`. Supporting those types in the model is easy. In the `RxSession` API we need one such facade per reactive style (which is what Vert.x is doing).

**Comment by gavinking** [comment]
> But it's pretty intrusive on use-site compared to `book.getAuthors().thenAccept( authors -> { ... } )`.

Well, I dunno, it's not much worse, IMO, and it has the *huge* advantage that people can use the same `Book` class in both regular Hibernate code and in Hibernate RX.

**Comment by FroMage** [comment]
As I said, we can certainly start with this and see if we have to improve it later.

**Comment by gavinking** [comment]
Actually it has a second massive advantage: in the case where I fetch the association *eagerly* using a join, I don't have to wade through `.thenAccept()` or whatever to get at the elements of the association. I can just access them directly using regular collection iteration.

**Comment by FroMage** [comment]
Well, that also means you can access `book.getAuthors()` and block by accident.

**Comment by gavinking** [comment]
Nope, it will throw.

**Comment by FroMage** [comment]
So it also impacts all the entity code that uses those relations, in which case the entities still have to be updated.

**Comment by gavinking** [comment]
@FroMage Nope. I don't know why you would say that.

**Comment by FroMage** [comment]
```java
@Entity
public class Foo {
   @OneToMany
   private List<Bar> bars = new ArrayList<>();

   public void addBar(Bar bar){
      getBars().add(bar);
   }
}
```

Then `foo.addBar(bar)` starts throwing and we need to rewrite it, no?

**Comment by gavinking** [comment]
No. You need to enable a fetch profile so that `bars` are fetched eagerly using an efficient SQL join instead of writing shitty Hibernate code that does lots of trips to and from the database. Just like you should have done already, in any nonshitty regular Hibernate code.

**Comment by FroMage** [comment]
So you're shifting requirements. It started with "reuse existing entities" and now it's "reuse existing nonshitty entities" ;) I fear every new such requirement reduces the set size.

**Comment by gavinking** [comment]
But it's nothing to do with the entities themselves. This is an aspect of the code that *uses* the entities!

**Comment by FroMage** [comment]
I'm saying I've seen that code _in_ the entities super often.

**Comment by gavinking** [comment]
And that code in and of itself is perfectly fine and nonbroken.

**Comment by gavinking** [comment]
I have added a partial, and probably crappy implementation of this. It doesn't support many-valued associations, and it might not support all the correct semantics of Hibernate, so we need to review it tomorrow.

**Comment by gavinking** [comment]
Actually I would prefer that this worked like `Hibernate.initialize()`, and didn't require a reference to the `RxSession`. But that's hard to implement right now, just because of the way our code is structured.

**Comment by gavinking** [comment]
Closing this one because I opened #35.

**Comment by emmanuelbernard** [comment]
Just for info on my perspective, I understand the `thenAccept` model feels more intrusive in case you eargerly leaded but it's 100% predictable for both lazy and eagerly fetched associations and no exception will be thrown because somewhere else I did or did not forget to apply a correct profile. We can start with that model and test it but I am skeptical of these "runtime errors".
