### ISSUE TITLE
FlushModes

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-rx#24]
Setting the `FlushMode` for an `RxSession` is a purely in-memory operation and I don't see why it can't be declared as a blocking method.

**Comment by gavinking** [comment]
Small issue: currently the `RxSession` interface doesn't depend on anything in `org.hibernate` or `javax.persistence`. So what `FlushMode` type should we use here:

- `org.hibernate.FlushMode`
- `javax.persistence.FlushModeType`
- a new `org.hibernate.rx.Flush` enum?

WDYT, @FroMage @DavideD?

**Comment by FroMage** [comment]
@Sanne will probably have something to say here about stateless sessions?

**Comment by gavinking** [comment]
I have pushed a mockup for this. Please send your feedback.

**Comment by FroMage** [comment]
My feedback is that if we can avoid having a fourth enum (especially if the first existing three are _already_ in the user's classpath) we should.

**Comment by gavinking** [comment]
OK then that would mean depending on `org.hibernate` I guess.

**Comment by gavinking** [comment]
Done.
