### ISSUE TITLE
cascade persistence operations to associations

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-rx#34]
Cascading doesn't work. This is a bit of a painful limitation and so we should investigate how hard it would be to fix it.

**Comment by gavinking** [comment]
So actually this doesn't look very scary. We need to do a copy/paste job on `org.hibernate.engine.internal.Cascade` and `org.hibernate.engine.spi.CascadingActions`. And that's < 1000 LOC.

**Comment by gavinking** [comment]
I made this sorta-work for cascade delete along a `@ManyToOne`. But my implementation is rubbish, so I'm not going to push it for now. Still, it's not impossible, I believe.

**Comment by gavinking** [comment]
Cascade persist and remove now work to some extent. I need to do some more testing, and I imagine it's likely we'll find bugs. But implementing this feature really helped me clarify the design of the whole system and what things are non-blocking and how it all has to work.

**Comment by gavinking** [comment]
So on the #34 branch I have this working for `@OneToMany`s. They don't work on `master` because of the issue with session identity.

So now that the most basic functionality seems to be working, I'm going to close this issue, and we can open additional issues if/when we run into bugs.

**Comment by mgonzaga1990** [comment]
https://github.com/hibernate/hibernate-reactive/issues/34#issuecomment-575895404
do you have an example for this? or is it in the quickstart already? I'm trying to implement cascade persist but not working if the parent id (which is my foreign key for my child table) is null.

**Comment by DavideD** [comment]
We have examples in our test cases: https://github.com/hibernate/hibernate-reactive/blob/master/hibernate-reactive-core/src/test/java/org/hibernate/reactive/CascadeTest.java#L192

What are you trying to do exactly? What didn't work? Some examples of the entities you are mapping would help.
