### ISSUE TITLE
RxSession.fetch() for lazy @OneToMany associations

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-rx#35]
Following on from #18 and #12, we need to let you call `fetch()` on a lazy @OneToMany association.

@DavideD this is a follow-up to your latest work.

**Comment by gavinking** [comment]
To be clear, @DavideD, this issue just involves adding a `DefaultRxInitializeCollectionEventListener` and an `RxOneToManyLoader` that we can hang off the `OneToManyPersister`. We don't want to do more than that for now. Writing a whole `RxCollectionPersister` is off the cards until we come to #44 and #45.

**Comment by DavideD** [comment]
Working on it
