### ISSUE TITLE
patch hibernate-core to make it easier to implement hibernate-rx

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-rx#36]
I'm going to do this work on a branch.

**Comment by gavinking** [comment]
I've submitted https://github.com/hibernate/hibernate-orm/pull/3176.

**Comment by gavinking** [comment]
The changes to Hibernate RX itself are on the #31 branch of this repo.

**Comment by gavinking** [comment]
I was able to delete almost 500 lines of code, and move all the code under `org.hibernate.rx`.

**Comment by gavinking** [comment]
At least two bugs were fixed purely as a side-effect of this refactoring.

**Comment by gavinking** [comment]
Alright, so now @Sanne has applied my PR, we have to decide whether to merge the #36 branch into master. I think we should, since it has all sorts of useful new stuff, and also I don't want us to struggle with maintaining two branches when we don't even have users yet.

*However* it does mean that you will need a snapshot build of Hibernate to try out Hibernate RX. I *think* that's acceptable but WDYT, @DavideD @Sanne @FroMage @emmanuelbernard ?

**Comment by Sanne** [comment]
sure, I hope the RX team can keep the momentum going: use a snapshot for some days, but also an ORM tag isn't going to take long.

**Comment by Sanne** [comment]
P.S. to deploy a snapshot from ORM's master into your local Maven cache use:

    ./gradlew publishToMavenLocal

Next, the build of RX should be patched; this section is missing "mavenLocal()":

    repositories {
        jcenter()
        mavenCentral()
    }

**Comment by gavinking** [comment]
@Sanne yep that's what I'm doing. I already patched the build on the #36 branch.

**Comment by gavinking** [comment]
I merged. We need to develop against a single branch.
