### ISSUE TITLE
Optional decision

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-rx#52]
So I want to know are we really going to force `Optional<Entity>` down everyone's throat? I've been using it the last few day, and yew, it really is just as crappy as I figured it was, *nothing* like a proper option or nullable type.

But if that's where the whole Java world is going ... well, I dunno, I guess we should be consistent.

Thoughts?

**Comment by gavinking** [comment]
@FroMage?

**Comment by FroMage** [comment]
Don't ask me I hate it. But a lot of people like it. IMO it should be opt-in with both options.

**Comment by gavinking** [comment]
Pfff. Well currently it's on methods like `find()` and `fetch()`, so pretty hard to opt out...

**Comment by gavinking** [comment]
The thing about it is that it not only doesn't protect you from bugs, since almost all of the time all you're going to do is just call `get()` on it (calling `isPresent()` first is just a worse way to write `!=null`), but it actually can be a *source* of bugs since `Optional<Object>` is assignable to `Object`!

**Comment by gavinking** [comment]
You can even write shit like this:

```if ( thing.isPresent() ) {
    ...
    if (thing == otherThing) { ... }
}`

From that point of view, you were safer *without it*.

**Comment by gavinking** [comment]
I think I would lean towards removing it `Optional` from our APIs, unless someone speaks up in its favor.

**Comment by gavinking** [comment]
OK, given the votes in favor from @vietj, @FroMage, @aguibert, and the lack of strong objection from anybody else, I think I'll go ahead and merge #93.

**Comment by DavideD** [comment]
OK, sounds good to me

**Comment by DavideD** [comment]
Plus, if we realize that it makes sense to have Optional somewhere we can always add the method later

**Comment by gavinking** [comment]
Done.
