### ISSUE TITLE
Keep track of methods that are copies of the ORM ones with an annotation

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-rx#83]
Sometimes we have to duplicate some methods from ORM because their scope makes them invisible to us. It would be nice to have an annotation to keep track of these methods so that we can update ORM when possible and won't forget about it.
Does it make sense? Not sure about the name.

**Comment by gavinking** [comment]
I would say in cases like this we should make the patch for core right away, even if it's not immediately integrated.

**Comment by DavideD** [comment]
Fair enough.
I was trying to be lazy :)
